version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: pipelet_sandbox
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    env_file: .env
    environment:
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "5000:5000"   # Flask API
      - "9000:9000"   # OCPP WS (später genutzt)
    command: ["python", "wsgi.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_BASE=http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
