FROM node:18-alpine AS deps
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY frontend .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
ENV HOST=0.0.0.0
EXPOSE 5173
COPY --from=deps /app/node_modules ./node_modules
COPY frontend .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
